apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-csp
  namespace: private-cloud
  labels:
    app.kubernetes.io/name: opencloud
data:
  csp.yaml: |
    directives:
      child-src:
        - "'self'"
      connect-src:
        - "'self'"
        - "blob:"
        - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
        - "https://update.opencloud.eu/"
      default-src:
        - "'none'"
      font-src:
        - "'self'"
      frame-ancestors:
        - "'self'"
      frame-src:
        - "'self'"
        - "blob:"
        - "https://embed.diagrams.net/"
        - "https://replace-with-onlyoffice-hostname/"
      img-src:
        - "'self'"
        - "data:"
        - "blob:"
        - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
        - "https://replace-with-onlyoffice-hostname/"
      manifest-src:
        - "'self'"
      media-src:
        - "'self'"
      object-src:
        - "'self'"
        - "blob:"
      script-src:
        - "'self'"
        - "'unsafe-inline'"
      style-src:
        - "'self'"
        - "'unsafe-inline'"
        - "blob:"
      worker-src:
        - "'self'"
        - "blob:"
