apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - apps-configmap.yaml
  - app-registry-configmap.yaml
  - csp-configmap.yaml
  - deployment.yaml
  - service.yaml
  - public-service.yaml
