apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: private-cloud
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-pgvector
  namespace: private-cloud
automountServiceAccountToken: false
