apiVersion: v1
kind: PersistentVolume
metadata:
  name: stalwart-data
  labels:
    app.kubernetes.io/name: stalwart
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: private-cloud
    name: stalwart-data
  local:
    path: /tank/secure/backup/k0s/services/stalwart
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - replace-with-k0s-node
