apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart
  namespace: private-cloud
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stalwart-configuration
  namespace: private-cloud
automountServiceAccountToken: false
