apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - server-deployment.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
