apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-server-data
  labels:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/component: server-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/zabbix
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost
