apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-server
  namespace: private-cloud
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-web
  namespace: private-cloud
automountServiceAccountToken: false
