[SERVICE]
    Flush          1
    Grace          10
    Log_Level      warn

[INPUT]
    Name                tail
    Path                ${LOG_PATH}
    Tag                 application.file
    Key                 message
    Path_Key            source_file
    DB                  /state/tail.db
    DB.Sync             Normal
    DB.Compare_Filename true
    Read_From_Head      true
    Refresh_Interval    1
    Rotate_Wait         30
    Buffer_Max_Size     1M
    Skip_Long_Lines     On
    Mem_Buf_Limit       8M

[OUTPUT]
    Name             stdout
    Match            *
    Format           json_lines
    Json_Date_Key    collected_at
    Json_Date_Format iso8601
