apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grist-ingress
  namespace: private-cloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grist
  policyTypes: [Ingress]
  ingress:
    - ports:
        - {protocol: TCP, port: 8484}
