---
opencloud_namespace: private-cloud
opencloud_service_name: opencloud
opencloud_secret_name: opencloud-credentials
opencloud_dataset: tank/secure/backup/k0s/services/opencloud
opencloud_dataset_mountpoint: /tank/secure/backup/k0s/services/opencloud
opencloud_pv_name: opencloud-data
opencloud_pvc_name: opencloud-data
opencloud_bleve_pvc_name: bleve-data
opencloud_bleve_pv_name: bleve-data
opencloud_bleve_dataset_mountpoint: /tank/secure/backup/k0s/services/bleve
opencloud_pv_capacity: 10Ti
opencloud_kubeconfig: /run/private-cloud/kubeconfig
