private_cloud:
  stages:
    zfs: true
    k0s: true
    postgres: true
    meilisearch: true
    stalwart: true
    tika: true
    bleve: true
    onlyoffice: true
    opencloud: true
    grist: true
    affine: true
    zabbix_server: true
    zabbix_agent: true
  storage:
    disks:
      - /dev/disk/by-id/replace-with-first-disk
      - /dev/disk/by-id/replace-with-second-disk
  k0s:
    version: v1.36.2+k0s.0
    config_quota: 1G
    images_quota: 10G
    ephemeral_quota: 10G
  postgres:
    volume_size: 20G
    max_ram: 2Gi
  meilisearch:
    storage_size: 20G
    max_ram: 1Gi
  tika:
    storage_size: 5G
    max_ram: 1Gi
  bleve:
    storage_size: 20G
  onlyoffice:
    storage_size: 20G
    max_ram: 4Gi
    hostname: onlyoffice.example.com
    node_port: 30082
  opencloud:
    storage_size: 100G
    max_ram: 4Gi
    hostname: cloud.example.com
    node_port: 30920
  grist:
    storage_size: 50G
    max_ram: 2Gi
    database_name: grist
    database_username: grist
    default_email: admin@example.com
    hostname: grist.example.com
    node_port: 30848
  affine:
    storage_size: 100G
    max_ram: 4Gi
    redis_max_ram: 512Mi
    database_name: affine
    database_username: affine
    hostname: affine.example.com
    node_port: 30310
  stalwart:
    storage_size: 100G
    max_ram: 2Gi
    database_name: stalwart
    database_username: stalwart
    domain: example.com
    forwarding_domain: inbound.example.com
    hostname: mail.example.com
    acme_contact: postmaster@example.com
    admin_username: admin
    mailbox_username: user
    relay_host: mail.inbox.eu
    relay_port: 465
    relay_implicit_tls: true
    relay_username: user@example.com
    https_node_port: 30443
    smtp_node_port: 30025
    submissions_node_port: 30465
    submission_node_port: 30587
    imaps_node_port: 30993
  zabbix:
    storage_size: 5G
    database_name: zabbix
    database_username: zabbix
    server_node_port: 31051
    web_node_port: 30080
    hostname: private-cloud-zabbix
    admin_username: Admin
    agent_server_active: 127.0.0.1:31051
