apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - network-policy.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - migration-job.yaml
  - deployment.yaml
  - service.yaml
  - public-service.yaml
